services:
  redis:
    image: 'redis:7.4-rc2'
    container_name: 'redis'
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    labels:
      org.springframework.boot.service-connection: redis

volumes:
  redis:
    driver: local